
nombre=input('ingresar primer nombre ')
nombre_1=input('ingresar segundo nombre ')
apellido_1=input('ingresar primer apellido ')
apellido_2=input('ingresar segundo apellido ')
nombre=nombre.capitalize()
nombre_1=nombre_1.capitalize()
apellido_1=apellido_1.capitalize()
apellido_2=apellido_2.capitalize()
print(f'Mi nombre es:{nombre} {nombre_1} {apellido_1} {apellido_2}')
